name: Deploy next.js app to ec2

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.15

      - name: Generate SSH Key Pair
        run: |
          ssh-keygen -t rsa -b 4096 -f my-deploy-key -N ""
          cat my-deploy-key.pub

      - name: Upload Public Key to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: my-deploy-key
          port: 22
          script: |
            mkdir -p ~/.ssh
            echo "$(cat my-deploy-key.pub)" >> ~/.ssh/authorized_keys
            chmod 600 ~/.ssh/authorized_keys

      - name: Install dependencies
        run: |
          npm install
          npm run build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ./my-deploy-key
          port: 22
          script: |
            # Stop existing app
            pm2 stop nextjs || true

            # Create app directory
            mkdir -p /var/www/nextjs

            # Copy files to EC2
            rm -rf /var/www/nextjs/*
            scp -r ./ /var/www/nextjs

            # Install dependencies and start app
            cd /var/www/nextjs
            npm install --production
            npm run start -p 3000 &

            # Restart NGINX
            sudo systemctl restart nginx
